### PR TITLE
terms: tos-update

### PR DESCRIPTION
**Pull request by Stanislaw-bnk**

### CODE REVIEW

**Comment by gosiastyba** [comment]
@Stanislaw-bnk Przyznam, że nie jestem pewna, jakie mamy praktyki do mergowania w przypadku, gdy nie wszystkie checki są spełnione (tutaj ten nie jest: SEO CI / linkChecker (pull_request) ) (@artur-rs  może pomożesz?) Poza tym jednym nie mam więcej uwag.

**Comment by pietrushnic** [comment]
@gosiastyba This is a public repo where we use English. I already wrote internally what the issue is and how @Stanislaw-bnk should address that.

**Comment by Stanislaw-bnk** [comment]
The issue with the broken link is in the `style.html` directory. It is indeed a 404, but I'm not quite sure to what website should I change it (https://fontawesome.com/ ?), and if the change won't affect anything negatively on the Dasharo website if I just delete the link.
The broken links checker:
 `docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee
    --max-redirects 10 -a 403,429,500,502,503,999` when I tried to run it locally returned:
```
For more information, try '--help'.
bash: --max-redirects: command not found...
[sbieniek@3M11 dasharo-website]$ docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee --max-redirects 10 -a 403,429,500,502,503,999
error: the following required arguments were not provided:
  <inputs>...

Usage: lychee --max-redirects <MAX_REDIRECTS> --accept <ACCEPT> <inputs>...
```

**Comment by Stanislaw-bnk** [comment]
Yes, I have just tried to delete the links, the page rendered correctly at first sight, didn't notice any change. 
PR with the fix: https://github.com/Dasharo/dasharo-website/pull/55

**Comment by Stanislaw-bnk** [comment]
A new issue with the broken links checker: https://github.com/Dasharo/dasharo-website/issues/56

**Comment by pietrushnic** [comment]
@Stanislaw-bnk #55 merged.

**Comment by gosiastyba** [comment]
> @gosiastyba This is a public repo where we use English. 

@pietrushnic Understood. For clarity, I have included an English version of the comment.

**Comment by Asiderr** [comment]
@Stanislaw-bnk @pietrushnic I responded in https://github.com/Dasharo/dasharo-website/issues/56. 404 is an actual issue and must be fixed (not ignored) before merging.

**Comment by pietrushnic** [comment]
> 404 is an actual issue and must be fixed (not ignored) before merging.

@Asiderr sounds like automatic reply, this is precisely what @Stanislaw-bnk did in https://github.com/Dasharo/dasharo-website/pull/55

**Comment by Stanislaw-bnk** [comment]
> if you rebase on top of develop it should be fixed

@artur-rs Having a problem doing that, need a little help. Should I just follow the same instructions like for the [3mdeb website](https://github.com/3mdeb/3mdeb-website?tab=readme-ov-file#development-workflow)?
`After successful deployment on the beta environment, if a whole set of patches is merged in the develop branch, open a new PR to main. The reporter will verify changes and publish prod env. `
Would like to rebase the develop to main.

**Comment by pietrushnic** [comment]
@Stanislaw-bnk @gosiastyba those changes were not merged, when you plan to fix this PR?

**Comment by Stanislaw-bnk** [comment]
@Asiderr I would like to resolve the merge conflicts here, but the linkchecker says: `The logs for this run have expired and are no longer available.`. How should I proceed here?

**Comment by Asiderr** [comment]
@Stanislaw-bnk You have to rerun this pipeline. Trigger once again all of the tests.

**Comment by Stanislaw-bnk** [comment]
> You have to rerun this pipeline. Trigger once again all of the tests.

How can I re-run the tests without making any additional changes in the file?

**Comment by Asiderr** [comment]
@Stanislaw-bnk https://github.com/Dasharo/dasharo-website/actions/runs/7693514729?pr=54 -> `...` -> Rerun job

**Comment by Stanislaw-bnk** [comment]
> Rerun job

I know, the problem is there is no such option, only `Create status badge`

**Comment by Stanislaw-bnk** [comment]
@artur-rs Could you please help with the linkchecker fail here?

**Comment by artur-rs** [comment]
@Stanislaw-bnk I do not see this option as well, which is strange. Even the linkChecker log is empty.

**Comment by artur-rs** [comment]
@Stanislaw-bnk rebase did the work. Merging

**Pull request merged**
