### PR TITLE
Draft: Move faq to dasharo universe

### PR DESCRIPTION
**Pull request by pietrushnic**
This PR tries to get rid of duplication caused by the existence of two FAQs (dasharo.com and docs.dasharo.com). it aims to unify existing FAQa on the Dasharo Universe version.

This MR should not be merged until all following PRs are merged or closed:
- https://github.com/Dasharo/docs/pull/549
- https://github.com/Dasharo/docs/pull/550
- https://github.com/Dasharo/docs/pull/551
- https://github.com/Dasharo/docs/pull/552
- https://github.com/Dasharo/docs/pull/553
- https://github.com/Dasharo/docs/pull/554
- https://github.com/Dasharo/docs/pull/555
- https://github.com/Dasharo/docs/pull/556
- https://github.com/Dasharo/docs/pull/557

### CODE REVIEW

**Comment by artur-rs** [comment]
rebased cause of CI changes introduced recently

**Review by artur-rs — APPROVED** [review]

**Comment by miczyg1** [comment]
> This MR should not be merged until all following PRs are merged or closed

Simply awesome. Not even a single PR is closed or merged.

@pietrushnic do we plan to go back to the PRs listed in your above comment?

**Comment by pietrushnic** [comment]
@miczyg1 why is it important now?

**Comment by miczyg1** [comment]
@pietrushnic I saw many unfinished/floating/forgotten not-so-old PRs and checked if they could be merged or not. Eventually landed here. We have 33 open PRs and 48 branches on docs... Some cleanup (at least partial) would be great.

**Comment by pietrushnic** [comment]
@miczyg1 agree. We need resources to make it happen.

**Pull request merged**
